# Config

live_config_reload = true


# Environment

[env]
TERM = "xterm-256color"


# Behaviour

[selection]
save_to_clipboard = true

[scrolling]
history = 100000

[bell]
animation = "Ease"
duration  = 100
color     = "0xdedad4"


# Input

[keyboard]
bindings = [
  { key = "Right",  mods = "Alt",    chars = "\u001BF" }, # foward one word
  { key = "Left",   mods = "Alt",    chars = "\u001BB" }, # back one word
  { key = "Right",  mods = "Super",  chars = "\u0005" },  # end of the line
  { key = "Left",   mods = "Super",  chars = "\u0001" },  # start of the line
]


# Looks

[window]
dynamic_padding = true
decorations     = "Transparent"

[window.dimensions]
columns = 120
lines   = 40

[window.padding]
x = 5
y = 20

[cursor]
vi_mode_style = "Block"
blink_timeout = 0

[cursor.style]
shape     = "Beam"
blinking  = "Always"

[font]
size = 14.0

[font.normal]
family = "InputMono Nerd Font"
style  = "Regular"

[font.bold]
family = "InputMono Nerd Font"
style  = "Medium"


# One Dark Theme
#  source: https://gist.github.com/r-darwish/f8bb21a6c89a02c4bef76cc38bddad39

[colors]
draw_bold_text_with_bright_colors = true

# Default colors
[colors.primary]
background        = "0x21252b"
foreground        = "0xabb2bf"

# Bright and dim foreground colors
#  The dimmed foreground color is calculated automatically if it is not present.
#  If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
#  is `false`, the normal foreground color will be used.
dim_foreground    = "0x9a9a9a"
bright_foreground = "0xe6efff"

# Cursor colors
#  Colors which should be used to draw the terminal cursor. If these are unset,
#  the cursor color will be the inverse of the cell color.
#[colors.cursor]
#text   = "0x000000"
#cursor = "0xffffff"

# Normal colors
[colors.normal]
black   = "0x1e2127"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xd19a66"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0x828791"

# Bright colors
[colors.bright]
black   = "0x5c6370"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xd19a66"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0xe6efff"

# Dim colors
#  If the dim colors are not set, they will be calculated automatically based
#  on the `normal` colors.
[colors.dim]
black   = "0x1e2127"
red     = "0xe06c75"
green   = "0x98c379"
yellow  = "0xd19a66"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0x828791"

# Indexed Colors
#  The indexed colors include all colors from 16 to 256.
#  When these are not set, they're filled with sensible defaults.
#[[colors.indexed_colors]]
#index = 16
#color = "0x000000"

